package util;

import java.util.Arrays;
import java.util.List;

public class FinalData {
    public static final char MINUS_CHAR = '-';
    public static final int UNIT_CLASSES = 0;
    public static final int THOUSAND_CLASSES = 1;
    public static final String RUSSIAN = "Rus";
    public static final String MINUS_RUSSIAN = " минус";
    public static final String MINUS_ENGLISH = " minus";
    public static final String NOT_NUMBER_EXCEPTION = "Not number";
    public static final String NULL_EXCEPTION = "Null Exception";
    public static final String OUT_OF_BOUNDS = "Out Of Bounds";
    public static final String LOG4J_FILE = "log4j.properties";
    public static final String ZEROS = "000";
    public static final String EMPTY = "";
    public static final String STRING = " ";
    public static final String AND = " and";
    public static final String ONE = " одна ";
    public static final String TWO = " две ";
    public static final String OF = "ов";
    public static final String A = "а";
    public static final String I = "и";
    public static final String RUSSIAN_DIRECTORY = "DirectoryRussianWordsNumber.xls";
    public static final String ENGLISH_DIRECTORY = "DirectoryEnglishWordsNumber.xls";
    public static final String FILE_NOT_FOUND = "File not found";
    public static final String ERROR_INPUT_STREAM = "Error input stream file in workbook";
    public static final String ERROR_CLOSE_STREAM = "Error close stream";
    public static final String MINUS_ZERO = "-0";
    public static final String MINUS = "-";
    public static final String LANGUAGE = "Eng";
    public static final String ONE_HUNDRED = "100";
    public static final String ONE_HUNDRED_WORD = "one hundred";
    public static final String TEN = "10";
    public static final String ONE_HUNDRED_WITH_ZEROS_AT_BEGIN = "00000100";
    public static final String ONE_MILLION_ONE = "1000001";
    public static final String ONE_MILLION_ONE_WORD = "one million and one";
    public static final String NULL = null;
    public static final String NOT_NUMBER_VALUE = "Good morning!!!";
    public static final String ONE_HUNDRED_TWENTY_THREE = "123";
    public static final String ONE_HUNDRED_TWENTY_THREE_RUSSIAN_WORD = " сто двадцать три";
    public static final String ONE_HUNDRED_TWENTY_THREE_ENGLISH_WORD = " one hundred and twenty three";
    public static final String ONE_HUNDRED_TWENTY_THREE_THOUSAND_RUSSIAN_WORD = " сто двадцать три тысячи";
    public static final String ONE_HUNDRED_TWENTY_THREE_THOUSAND_ENGLISH_WORD = " one hundred twenty three thousand";
    public static final String ONE_HUNDRED_RUSSIAN_WORD = " сто";
    public static final String ONE_HUNDRED_ENGLISH_WORD = " one hundred";
    public static final String LANGUAGE_RUSSIAN = "Rus";
    public static final String LANGUAGE_ENGLISH = "Eng";
    public static final String NOT_NUMBER_FORMAT = "MMM";
    public static final String CELL_STRING = "Текст";
    public static final String CELL_NUMBER = "12345.0";
    public static final String CELL_DATA = "Mon Oct 09 00:00:00 MSD 2000";
    public static final String CELL_DOUBLE = "2.3";
    public static final String MINUS_ONE_HUNDRED = "-100";
    public static final String ONE_THOUSAND = "1000";
    public static final String ONE_TO_NINE = "123456789";
    public static final String NUMBER_WHO_OUT_OF_EXCEL_DIRECTORY = "1234567890123456789012345678901234567890123456789" +
            "012345678901234567890123456789012345678901234567890";
    public static final List<String> ONE_TO_NINE_SEGMENT = Arrays.asList("123", "456", "789");
    public static final List<String> ONE_TO_SIX_SEGMENT = Arrays.asList("123", "456");
    public static final List<String> RUSSIAN_DIFFERENCE_ARRAY_ZERO_TO_ONE_HUNDRED = Arrays.asList("ноль", "один", "два", "три");
    public static final List<String> ENGLISH_DIFFERENCE_ARRAY_ZERO_TO_ONE_HUNDRED = Arrays.asList("zero", "one", "two", "three");
    public static final List<String> RUSSIAN_DIFFERENCE_ONE_HUNDRED_TO_ONE_THOUSAND = Arrays.asList("сто", "двести");
    public static final List<String> RUSSIAN_DIFFERENCE_EXCEL_ARRAY = Arrays.asList("ноль", "один", "два", "три", "четыре");
    public static final List<String> ENGLISH_DIFFERENCE_EXCEL_ARRAY = Arrays.asList("zero", "one", "two");
    public static final List<String> RUSSIAN_ONE_HUNDRED_TO_ONE_THOUSAND = Arrays.asList("сто", "двести", "триста", "четыреста", "пятьсот", "шестьсот", "семьсот", "восемьсот", "девятьсот");
    public static final List<String> ENGLISH_DIFFERENCE_ONE_HUNDRED_TO_ONE_THOUSAND = Arrays.asList("one hundred", "two hundred", "three hundred");
    public static final List<String> RUSSIAN_DIFFERENCE_ONE_THOUSAND_TO_MAXIMUM_AVAILABLE_NUMBER = Arrays.asList("тысяч", "миллион", "миллиард");
    public static final List<String> ENGLISH_DIFFERENCE_ONE_THOUSAND_TO_MAXIMUM_AVAILABLE_NUMBER = Arrays.asList("thousand", "million", "billion", "trillion");
    public static final List<String> ENGLISH_ONE_HUNDRED_TO_ONE_THOUSAND = Arrays.asList("one hundred", "two hundred", "three hundred", "four hundred", "five hundred", "six hundred", "seven hundred", "eight hundred", "nine hundred");
    public static final List<String> RUSSIAN_ONE_THOUSAND_TO_MAXIMUM_AVAILABLE_NUMBER = Arrays.asList("тысяч", "миллион", "миллиард", "триллион", "квадриллион", "квинтиллион", "секстиллион", "септиллион", "октиллион", "нониллион", "дециллион", "андециллион", "дуодециллион", "тридециллион", "квадридециллион", "квинтидециллион", "секстидециллион", "септидециллион", "октидециллион", "нонидециллион", "децидециллион");
    public static final List<String> ENGLISH_ONE_THOUSAND_TO_MAXIMUM_AVAILABLE_NUMBER = Arrays.asList("thousand", "million", "billion", "trillion", "quadrillion", "quintillion", "sextillion", "septillion", "octillion", "quintillion", "decillion", "andecillion", "duodecillion", "tridecillion", "quadrillion", "quintidecillion", "sextidecillion", "septidecillion", "octidecillion", "nonidecillion", "decidecillion");
    public static final List<String> RUSSIAN_EXCEL_ARRAY = Arrays.asList("ноль", "один", "два", "три", "четыре", "пять", "шесть", "семь", "восемь", "девять", "десять", "одиннадцать", "двенадцать", "тринадцать", "четырнадцать", "пятнадцать", "шестнадцать", "семнадцать", "восемнадцать", "девятнадцать", "двадцать", "тридцать", "сорок", "пятьдесят", "шестьдесят", "семьдесят", "восемьдесят", "девяноста", "сто", "двести", "триста", "четыреста", "пятьсот", "шестьсот", "семьсот", "восемьсот", "девятьсот", "тысяч", "миллион", "миллиард", "триллион", "квадриллион", "квинтиллион", "секстиллион", "септиллион", "октиллион", "нониллион", "дециллион", "андециллион", "дуодециллион", "тридециллион", "квадридециллион", "квинтидециллион", "секстидециллион", "септидециллион", "октидециллион", "нонидециллион", "децидециллион");
    public static final List<String> ENGLISH_EXCEL_ARRAY = Arrays.asList("zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty", "thirty", "forty", "fifty", "sixty", "seventy", "eighty", "ninety", "one hundred", "two hundred", "three hundred", "four hundred", "five hundred", "six hundred", "seven hundred", "eight hundred", "nine hundred", "thousand", "million", "billion", "trillion", "quadrillion", "quintillion", "sextillion", "septillion", "octillion", "quintillion", "decillion", "andecillion", "duodecillion", "tridecillion", "quadrillion", "quintidecillion", "sextidecillion", "septidecillion", "octidecillion", "nonidecillion", "decidecillion");
    public static final List<String> RussianArrayZeroToOneHundred = Arrays.asList("ноль", "один", "два", "три", "четыре", "пять", "шесть", "семь", "восемь", "девять", "десять", "одиннадцать", "двенадцать", "тринадцать", "четырнадцать", "пятнадцать", "шестнадцать", "семнадцать", "восемнадцать", "девятнадцать", "двадцать", "двадцать один", "двадцать два", "двадцать три", "двадцать четыре", "двадцать пять", "двадцать шесть", "двадцать семь", "двадцать восемь", "двадцать девять", "тридцать", "тридцать один", "тридцать два", "тридцать три", "тридцать четыре", "тридцать пять", "тридцать шесть", "тридцать семь", "тридцать восемь", "тридцать девять", "сорок", "сорок один", "сорок два", "сорок три", "сорок четыре", "сорок пять", "сорок шесть", "сорок семь", "сорок восемь", "сорок девять", "пятьдесят", "пятьдесят один", "пятьдесят два", "пятьдесят три", "пятьдесят четыре", "пятьдесят пять", "пятьдесят шесть", "пятьдесят семь", "пятьдесят восемь", "пятьдесят девять", "шестьдесят", "шестьдесят один", "шестьдесят два", "шестьдесят три", "шестьдесят четыре", "шестьдесят пять", "шестьдесят шесть", "шестьдесят семь", "шестьдесят восемь", "шестьдесят девять", "семьдесят", "семьдесят один", "семьдесят два", "семьдесят три", "семьдесят четыре", "семьдесят пять", "семьдесят шесть", "семьдесят семь", "семьдесят восемь", "семьдесят девять", "восемьдесят", "восемьдесят один", "восемьдесят два", "восемьдесят три", "восемьдесят четыре", "восемьдесят пять", "восемьдесят шесть", "восемьдесят семь", "восемьдесят восемь", "восемьдесят девять", "девяноста", "девяноста один", "девяноста два", "девяноста три", "девяноста четыре", "девяноста пять", "девяноста шесть", "девяноста семь", "девяноста восемь", "девяноста девять");
    public static final List<String> EnglishArrayZeroToOneHundred = Arrays.asList("zero", "one", "two", "three", "four", "five", "six", "seven", "eight", "nine", "ten", "eleven", "twelve", "thirteen", "fourteen", "fifteen", "sixteen", "seventeen", "eighteen", "nineteen", "twenty", "twenty one", "twenty two", "twenty three", "twenty four", "twenty five", "twenty six", "twenty seven", "twenty eight", "twenty nine", "thirty", "thirty one", "thirty two", "thirty three", "thirty four", "thirty five", "thirty six", "thirty seven", "thirty eight", "thirty nine", "forty", "forty one", "forty two", "forty three", "forty four", "forty five", "forty six", "forty seven", "forty eight", "forty nine", "fifty", "fifty one", "fifty two", "fifty three", "fifty four", "fifty five", "fifty six", "fifty seven", "fifty eight", "fifty nine", "sixty", "sixty one", "sixty two", "sixty three", "sixty four", "sixty five", "sixty six", "sixty seven", "sixty eight", "sixty nine", "seventy", "seventy one", "seventy two", "seventy three", "seventy four", "seventy five", "seventy six", "seventy seven", "seventy eight", "seventy nine", "eighty", "eighty one", "eighty two", "eighty three", "eighty four", "eighty five", "eighty six", "eighty seven", "eighty eight", "eighty nine", "ninety", "ninety one", "ninety two", "ninety three", "ninety four", "ninety five", "ninety six", "ninety seven", "ninety eight", "ninety nine");
}
